default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: jeremydwayne_test

production:
  adapter: postgresql
  pool: 5
  encoding: unicode
  database: <%= ENV["DB_PRODUCTION"] %>
  username: <%= ENV["DB_PRODUCTION_USER"] %>
  password: <%= ENV["DB_PASS"] %>
  port:     <%= ENV["DB_PRODUCTION_PORT"] %>
