default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: jeremydwayne_test

production:
  database: <%= ENV['DB_PRODUCTION'] %>
  username: <%= ENV['DB_PRODUCTION_USER'] %>
  host: ""
  adapter: postgresql
  password: <%= ENV['DB_PASS'] %>
  pool: 5
  reconnect: false
