default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: jeremydwayne_test

production:
  database: jeremydwayne_production
  username: deploy
  adapter: postgresql
  host: jeremydwayne.com
  password: <%= ENV['DB_PASS'] %>
  pool: 5
  reconnect: false
