default: &default
  pool: 5
  timeout: 5000

development:
  <<: *default
  adapter: sqlite3
  database: db/development.sqlite3

test:
  <<: *default
  adapter: sqlite3
  database: jeremydwayne_test

production:
  adapter: postgresql
  pool: 5
  encoding: unicode
  database: jeremydwayne_production
  username: jeremydwayne_production
  password: <%= ENV["DB_PASS"] %>
